apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: fernsuyama/api-bootcamp-produto
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin
